import assert from 'node:assert/strict';
import { getHeaderHints } from './nori-header.mjs';
const empty = { total: 0, count: 0, previousTotal: 0, topCategory: null, bills: 0, paidBills: 0 };
assert.equal(getHeaderHints(empty, 'th').length, 1);
assert.match(getHeaderHints(empty, 'en')[0].text, /No expenses/);
const full = { total: 1500, count: 3, previousTotal: 2000, topCategory: { name: 'Food', amount: 1000 }, bills: 2, paidBills: 2 };
const hints = getHeaderHints(full, 'en');
assert.equal(hints.length, 4);
assert.match(hints[1].text, /Food/);
assert.equal(hints[2].asset, 'teftel-cat-21');
assert.match(hints[3].text, /Previous full cycle/);
assert.match(getHeaderHints({ ...full, paidBills: 1 }, 'th')[2].text, /1 จาก 2/);
console.log('Header hints verified for empty cycles, categories, paid and pending bills.');
