import assert from 'node:assert/strict';
import { onboardingPlan } from './onboarding-presets.mjs';
const body = { language: 'th', categories: ['food', 'food', 'travel'], walletName: ' เงินสด ', initialBalance: 0 };
const plan = onboardingPlan(body);
assert.equal(plan.categories.length, 3);
assert.equal(plan.categories[0].name, 'อาหาร');
assert.equal(plan.categories[2].type, 'income');
assert.equal(plan.wallet.name, 'เงินสด');
assert.equal(plan.wallet.initialBalance, 0);
assert.equal(onboardingPlan({ ...body, initialBalance: null }).wallet.initialBalance, null);
assert.equal(onboardingPlan({ ...body, language: 'en' }).categories[0].name, 'Food');
for (const change of [{ categories: [] }, { categories: ['unknown'] }, { walletName: ' ' }, { initialBalance: '100' }, { language: 'xx' }]) assert.throws(() => onboardingPlan({ ...body, ...change }));
console.log('Onboarding setup checks passed');
